---
title: "Random_Presentation"
author: "Sandeep Anand"
date: "June 4, 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Slide 2

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)

# Head
head(mtcars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

## Your First Map

```{r Maps1, echo=FALSE}

library(leaflet)
set.seed(2016-04-25)
df<-data.frame(lat = runif(20, min=39.2, max=39.3),
               lng = runif(20, min=-76.6, max=-76.5))
df %>% leaflet() %>% addTiles() %>% addMarkers()
```

## Mapping clusters

```{r Mapping Clusters, echo=FALSE}

df <- data.frame(lat = runif(500, min=39.25, max=39.35),
                 lng = runif(500, min=-76.65, max=-76.55))

df %>% 
  leaflet() %>% 
  addTiles() %>%
  addMarkers(clusterOptions = markerClusterOptions())

```

# Map with Different Colors

```{r Mapping with Different colors, echo=FALSE}

df <- data.frame(lat = runif(20, min=39.5, max=39.6),
                 lng = runif(20, min=-76.5, max=-76.4),
                 colors = sample(c("red", "blue", "green"), 20, replace = TRUE),
                 stringAsFactors=FALSE
                 )
df %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircleMarkers(color=df$col) %>%
  addLegend(labels = LETTERS[1:3], colors = c("blue", "red", "green"))
  
  

```
